config/routes.rb
Rails.application.routes.draw do
  resources :requests
  resources :events
  resources :users
  root 'welcome#index'

  # Routes for create session
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # Routes for adding users to events
  get '/users/:id/friends' => 'users#friends'
  post '/event/:id/users' => 'events#add_user'
  delete '/event/:id/users' => 'events#delete_user'

  # Routes for display other's calender
  get '/event/:id/guest/:user_id' => 'events#guest'
  get ':current_id/guestviews/:user_id' => 'users#guest_view'

  # Routes for creating, accepting, declining and showing friends
  post '/requests/new/:current_user_id/:user_id' => 'requests#create'
  post 'requests/:id' => 'requests#accept_request'
  delete '/requests/:id' => 'requests#destroy'
  get '/users/:id/requests' => 'users#view_requests'
  delete ':id/unfriend/:user_id' => 'users#unfriend'
end

app/models/user.rb
# Required for password hash
require 'bcrypt'

# Create user table
class User < ActiveRecord::Base
  include BCrypt

  has_many :events
  has_many :requests
  has_many :users_friends
  has_many :friends, through: :users_friends

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: { minimum: 2 }
  validates :name, length: { maximum: 50 }

  validates :email, presence: true
  validates :email, length: { minimum: 2 }
  validates :email, length: { maximum: 50 }

  validates :password, presence: true
  validates :password, presence: { minimum: 2 }
  validates :password, presence: { maximum: 20 }

  def password
    @password ||= Password.new(password_hash) unless password_hash.nil?
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @events = Event.all
  end

  def guest_view
    @user = User.find(params[:current_id])
    @view_target = User.find(params[:user_id])
    @events = Event.all
    render :guest
  end

  def unfriend
    @user1 = User.find(params[:id])
    @user2 = User.find(params[:user_id])

    # Remove from each other's friend
    @user1.friends.delete(@user2)
    @user2.friends.delete(@user1)

    redirect_to current_user
  end

  def view_requests
    @user = User.find(params[:id])
    render :requests
  end

  def friends
    @user = User.find(params[:id])
    render :friends
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    @user.friends
    if @user.save
      # Sign user in to its session
      session[:user_id] = @user.id
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)

      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    # Reset the sesion
    reset_session
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:name, :password, :email)
  end
end

app/helpers/users_helper.rb
# Helper
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, class: "form_label" %><br>
    <%= f.text_field :name, class: "form_field" %>
  </div>
  <div class="field">
    <%= f.label :password, class: "form_label" %><br>
    <%= f.password_field :password, class: "form_field" %>
  </div>
  <div class="field">
    <%= f.label :email, class: "form_label" %><br>
    <%= f.text_field :email, class: "form_field" %>
  </div>
  <div class="actions">
    <%= f.submit "Create User", :class => "form_button" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/friends.html.erb
<% @user = User.find(params[:id])%>
<% @friends = @user.friends %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.name %></td>
        <td><%= friend.email %></td>
		<td><%= link_to 'Show', "/#{current_user.id}/guestviews/#{friend.id}", :class => 'link_button' %></td>
		<td><%= link_to 'Unfriend', "/#{current_user.id}/unfriend/#{friend.id}", method: :delete, :class => 'link_button' %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/guest.html.erb
<p id="notice"><%= notice %></p>

<% @events = Event.all %>

<%= month_calendar events: @events do |date, events|%>
  <%= date.day %>
  <% events.each do |event| %>
    <div>

    <%# Go through all events and check if the view target is a participant of the event. Display
    the event and a link to join the event%>
    <% if event.users.include? @view_target %>
      <li><%= link_to event.name, "/event/#{event.id}/guest/#{current_user.id}" %></li>
        <% if event.users.include? current_user %>
        <%= link_to 'Leave', "/event/#{event.id}/users", method: :delete %>
        <% else %>
        <%= link_to 'Join', "/event/#{event.id}/users", method: :post %>
        <% end %>
      <% end %>

    </div>



  <% end %>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<% if logged_in? %>
  <div id="table">
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <div id="table">
        <td><%= user.name %></td>
      </div>

        <div id="table">
        <td><%= user.email %></td>
      </div>
        <% if user == current_user %>
        <td><%= link_to 'Show', user, :class => 'link_button' %></td>
        <% else %>
          <%if user.friends.include? current_user %> 
          <td><%= link_to 'Show', "#{current_user.id}/guestviews/#{user.id}", :class => 'link_button' %></td>
              <td><%= link_to 'Unfriend', "/#{current_user.id}/unfriend/#{user.id}", method: :delete, :class => 'link_button' %> </td>
              
          <% else %>
          <td><%= link_to 'Send Friend Request', "/requests/new/#{current_user.id}/#{user.id}", method: :post, :class => 'link_button' %></td>
          <% end %>
        <% end %>

        <% if user == current_user%>
          <td><%= link_to 'Edit', edit_user_path(user), :class => 'link_button' %></td>
          <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' }, :class => "link_button" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>
<% else %>
    <div id='message2'>
      <h4> Hi, you are not currently logged in </h4>
      <h4> Click below to log in or sign up </h4>
      <p> <a class='button1' href='/login'>Log in</a> </p>
      <p> <a class='button2' href='/users/new'>Sign Up</a></p>
    </div>
<% end %>
<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<a class="user_button" href="/">Back</a>

app/views/users/requests.html.erb
<% @requests = Request.all %>
<% count = 0 %>
<% @requests.each do |request| %>
	<% if request.to_id == @user.id %>
		<% count = count + 1 %>
		<% check_user = User.find_by_id(request.from_id) %>
		<% if check_user %>
			<% from = User.find(request.from_id).name%>
			<% if @user.friends.include? User.find(request.from_id) %>
				<% @requests.delete(request) %>
			<% else %>
			<td><%= 'You have received a friend request from ' + "#{from}. " + 'Please respond to the request.'%>
	        <td><%= link_to 'Accept Friend Request', request, method: :post %></td>
       		 <td><%= link_to 'Decline Friendship', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
       		 <% end %>
       	<% else %>
       		<% @requests.delete(request) %>
       		<%= 'Currently, you do not have any friend request' %>
       	<% end %>
	<% end %>
<% end %>

	<% if count == 0 %>
	<%= 'Currently, you do not have any friend request' %>
	<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= month_calendar events: @events do |date, events|%>
	<%= date.day %>
	<% events.each do |event| %>
		<div>
		<% user_id = event.creator_id%>
		<% check_user = User.find_by_id(user_id) %>
		<% if check_user %>
			<% if event.creator_id == current_user.id %>
				<li><%=link_to event.name, event %></li>
				<%=link_to 'Delete', event, method: :delete %>
			<% elsif event.users.include? current_user %>
				<li><%=link_to event.name, event %></li>
				<%=link_to 'Leave', "/event/#{event.id}/users", method: :delete %>
			<% end %>
		<% else %>
			<% events.delete(event)%>
		<% end %>
		</div>
	<% end %>
<% end %>

<p><%= link_to 'Add Event', new_event_path, :class => 'link_button' %></p>