config/routes.rb
Rails.application.routes.draw do
  resources :requests
  resources :events
  resources :users
  root 'welcome#index'

  # Routes for create session
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # Routes for adding users to events
  get '/users/:id/friends' => 'users#friends'
  post '/event/:id/users' => 'events#add_user'
  delete '/event/:id/users' => 'events#delete_user'

  # Routes for display other's calender
  get '/event/:id/guest/:user_id' => 'events#guest'
  get ':current_id/guestviews/:user_id' => 'users#guest_view'

  # Routes for creating, accepting, declining and showing friends
  post '/requests/new/:current_user_id/:user_id' => 'requests#create'
  post 'requests/:id' => 'requests#accept_request'
  delete '/requests/:id' => 'requests#destroy'
  get '/users/:id/requests' => 'users#view_requests'
  delete ':id/unfriend/:user_id' => 'users#unfriend'
end

app/models/event.rb
# Event table
class Event < ActiveRecord::Base
  belongs_to :creator
  has_many :events_users
  has_many :users, through: :events_users
end

app/controllers/events_controller.rb
# Event Controller
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # Render guest view for calendar
  def guest
    @current_user = User.find(params[:user_id])
    @event = Event.find(params[:id])
    render :guest_view
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.creator_id = current_user.id
    @event.users.append(current_user)
    respond_to do |format|
      if @event.save
        format.html { redirect_to current_user, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Add user to event
  def add_user
    @event = Event.find(params[:id])
    @event.users.append(current_user) unless @event.users.include? current_user
    redirect_to current_user
  end

  # remove user from event
  def delete_user
    @event = Event.find(params[:id])
    @event.users.delete(current_user)
    redirect_to current_user
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:name, :description, :start_time, :end_time, :creator_id)
  end
end

app/helpers/events_helper.rb
# Helper
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="event_field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="event_field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="event_field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="event_field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="event_actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<p><a class="event_button" href="/users/<%= current_user.id %>">Cancel</a><p/>

app/views/events/guest_view.html.erb
<p id="notice"><%= notice %></p>

<% current_user = @current_user %>

<div class="event_info">
<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time %>
</p>

<p>
  <strong>Creator:</strong>
  <% user_id = @event.creator_id %>
  <% user = User.find(user_id) %>
  <%= user.name %>
</p>

<p>
    <strong>Participants:</strong>
  <% users = @event.users %>
  <% users.each do |user| %>
    <td><%= user.name %></td>
  <% end %>
</p>
</div>
<p>        <% if @event.users.include? current_user %>
        <%= link_to 'Leave', "/event/#{@event.id}/users", method: :delete, :class => "event_button_1" %>
        <% else %>
        <%= link_to 'Join', "/event/#{@event.id}/users", method: :post, :class => "event_button_1" %>
        <% end %>
</p>
<p><a class="event_button" href="/<%=current_user.id%>/guestviews/<%= @event.creator_id%>">Back</a></p>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Creator</th>
      <th>Participants</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
	<% if event.creator_id == current_user.id %>
      		<tr>
        	<td><%= event.name %></td>
        	<td><%= event.description %></td>
       	 	<td><%= event.start_time %></td>
        	<td><%= event.end_time %></td>
		<% user_id = event.creator_id %>
		<% user = User.find(user_id) %>
        	<td><%= user.name %></td>
		<% event.users.each do |participant|%>
		<td><%= participant.name%></td>
		<% end %>
        	<td><%= link_to 'Show', event %></td>
        	<td><%= link_to 'Edit', edit_event_path(event) %></td>
        	<td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      		</tr>
	<% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= month_calendar events: @events do |date, events|%>
	<%= date %>
	<% events.each do |event| %>
		<div>
		<% if event.creator_id == current_user.id %>
			<%= event.name %>
		<% end %>
		</div>
	<% end %>
<% end %>


<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<p><%= render 'form' %></p>

<a class="event_button" href="/users/<%= current_user.id %>">Cancel</a>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<div class="event_info">
<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time %>
</p>

<p>
  <strong>Creator:</strong>
  <% user_id = @event.creator_id %>
  <% user = User.find(user_id) %>
  <%= user.name %>
</p>

<p>
    <strong>Participants:</strong>
  <% users = @event.users %>
  <% users.each do |user| %>
    <td><%= user.name %></td>
  <% end %>
</p>

</div>

<p><%= link_to 'Edit', edit_event_path(@event), :class => "event_button_1" %></p>
        <td><%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' }, :class => "event_button_1" %></td>
<p><a class="event_button" href="/users/<%= current_user.id %>">Cancel</a></p>