config/routes.rb
Rails.application.routes.draw do
  resources :requests
  resources :events
  resources :users
  root 'welcome#index'

  # Routes for create session
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # Routes for adding users to events
  get '/users/:id/friends' => 'users#friends'
  post '/event/:id/users' => 'events#add_user'
  delete '/event/:id/users' => 'events#delete_user'

  # Routes for display other's calender
  get '/event/:id/guest/:user_id' => 'events#guest'
  get ':current_id/guestviews/:user_id' => 'users#guest_view'

  # Routes for creating, accepting, declining and showing friends
  post '/requests/new/:current_user_id/:user_id' => 'requests#create'
  post 'requests/:id' => 'requests#accept_request'
  delete '/requests/:id' => 'requests#destroy'
  get '/users/:id/requests' => 'users#view_requests'
  delete ':id/unfriend/:user_id' => 'users#unfriend'
end

app/models/request.rb
# A item in request has from id and to id
class Request < ActiveRecord::Base
  belongs_to :from
  belongs_to :to
end

app/controllers/requests_controller.rb
# Request controller
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy, :accept_request]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new/{#current_user}/{#target_user}
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(from_id: current_user.id, to_id: params[:user_id])
    respond_to do |format|
      if @request.save
        format.html { redirect_to current_user, notice: 'Friend request successfully sent.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  def accept_request
    from_user = User.find(@request.from_id)
    to_user = User.find(@request.to_id)
    from_user.friends.append(to_user)
    to_user.friends.append(from_user)
    @request.destroy

    respond_to do |format|
      format.html { redirect_to current_user, notice: 'You have accepted the friend request.' }
      format.json { head :no_content }
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @respondent = User.find(@request.to_id)
    @request.destroy
    respond_to do |format|
      format.html { redirect_to @respondent, notice: 'You have declined the friend request.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_request
    @request = Request.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def request_params
    params.require(:request).permit(:from_id, :to_id)
  end
end

app/helpers/requests_helper.rb
# Helper
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from_id %><br>
    <%= f.text_field :from_id %>
  </div>
  <div class="field">
    <%= f.label :to_id %><br>
    <%= f.text_field :to_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Requests</h1>

<table>
  <thead>
    <tr>
      <th>From</th>
      <th>To</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <% @requests.each do |request| %>
  <% if request.to_id == current_user.id%>

  <% end %>
<% end %>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.from_id %></td>
        <td><%= request.to_id %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>

        <td><%= link_to 'Accept Friend Request', request, method: :post %></td>
        <td><%= link_to 'Decline Friendship', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form' %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From:</strong>
  <%= @request.from_id %>
</p>

<p>
  <strong>To:</strong>
  <%= @request.to_id %>
</p>



<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>